name: Lint Code

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npx eslint .
      
    - name: Check for linting errors
      run: |
        if [ $? -ne 0 ]; then
          echo "❌ Linting failed. Please fix the issues above."
          exit 1
        else
          echo "✅ All code passed linting checks!"
        fi
